# Generated by Django 5.1.6 on 2025-03-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
