# Generated by Django 5.1.6 on 2025-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('returned', 'Returned'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
