# Generated by Django 5.1.6 on 2025-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('processing', 'Processing'), ('pending', 'Pending'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
