# Generated by Django 5.1.6 on 2025-03-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('returned', 'Returned'), ('delivered', 'Delivered'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
